### PR TITLE
Make setup.py not import PyOpenSSL by moving the implementation

### PR DESCRIPTION
**Pull request by delfick**
Hello,

If you don't already have pyOpenSSL installed, setup will fail because it eventually tries to import pyOpenSSL and fails.

Can we have something like this PR where the implementation is seperate to the version?

Thanks

Stephen.

### CODE REVIEW

**Comment by delfick** [comment]
hey @horazont I was just wondering if you had a chance to look at this yet?

Thanks

**Comment by horazont** [comment]
It cannot work that way.

I want the names to be importable from the `aioopenssl` package directly, so I applied a different fix. Please check with current devel whether this fix is sufficient for you.

Thank you very much for reporting this issue, and also I am sorry that you opening the issue got lost in the noise of my inbox.

**Comment by delfick** [comment]
Fair enough, no probs :)

Are you sure you pushed your different fix? There still seems to just be 3 commits there....

**Comment by horazont** [comment]
Àh, yes, fixed.

**Comment by delfick** [comment]
That looks good to me!

Thanks!

**Comment by horazont** [comment]
Released as v0.2.

**Comment by delfick** [comment]
champion!

**Pull request closed without merging**
